#!/usr/bin/env ruby
# frozen_string_literal: true

# ---------------------------------------------------------------------------
# Generates the LaTeX sources of the CV from the very same `_data/*.yml` files
# that Jekyll renders the website from, so the two can never drift apart.
#
#   _data/*.yml  --(this script)-->  cv/generated/*.tex  --(latexmk)--> PDF
#
# Run it through `scripts/build_cv.sh`, which also compiles the PDF.
# Uses only the Ruby standard library (Jekyll already requires Ruby).
# ---------------------------------------------------------------------------

require 'yaml'
require 'fileutils'

ROOT      = File.expand_path('..', __dir__)
DATA_DIR  = File.join(ROOT, '_data')
OUT_DIR   = File.join(ROOT, 'cv', 'generated')
BANNER    = "%% Generated by scripts/generate_cv.rb from _data/*.yml.\n" \
            "%% DO NOT EDIT BY HAND -- edit the YAML files and rebuild.\n\n"

def load_data(name)
  path = File.join(DATA_DIR, "#{name}.yml")
  File.exist?(path) ? (YAML.load_file(path) || {}) : {}
end

# --- LaTeX escaping --------------------------------------------------------

# Replacements are applied with the block form of `gsub` on purpose: in a
# replacement *string* Ruby reads `\\&` as "the whole match", which would
# silently leave ampersands unescaped.
TEX_ESCAPES = {
  '\\' => '\textbackslash{}',
  '&' => '\&', '%' => '\%', '$' => '\$', '#' => '\#', '_' => '\_',
  '{' => '\{', '}' => '\}',
  '~' => '\textasciitilde{}', '^' => '\textasciicircum{}',
  '–' => '--', '—' => '---',
  '‘' => '`', '’' => "'", '“' => '``', '”' => "''",
  '…' => '\ldots{}'
}.freeze
TEX_PATTERN = Regexp.union(TEX_ESCAPES.keys).freeze

def tex(value)
  value.to_s.gsub(TEX_PATTERN) { |match| TEX_ESCAPES[match] }
end

# A URL still needs `#` and `%` escaped for hyperref, but nothing else.
URL_ESCAPES = { '#' => '\#', '%' => '\%' }.freeze

def tex_url(value)
  value.to_s.gsub(/[#%]/) { |match| URL_ESCAPES[match] }
end

def section(title, body)
  "\\begin{rSection}{\\large #{title}}\n\n#{body.strip}\n\n\\end{rSection}\n"
end

def write(filename, content)
  # Always UTF-8: the shell locale must not decide how accented names are written.
  File.write(File.join(OUT_DIR, filename), BANNER + content, encoding: 'utf-8')
  puts "  wrote cv/generated/#{filename}"
end

# --- Data ------------------------------------------------------------------

profile   = load_data('profile')
experience = load_data('experience')
publications = load_data('publications')
grants    = load_data('research_grants')
awards    = load_data('awards')
service   = load_data('academic_service')

PRIMARY_NAME = profile['primary_name'].to_s
AUTHOR_MARKS = profile.fetch('cv_author_marks', true)

FileUtils.mkdir_p(OUT_DIR)
puts "Generating CV sources from _data/*.yml"

# --- Header (name + contact line) -----------------------------------------

# Each entry is [destination, icon, printed label]. Following the website, the
# e-mail address is printed in full while the rest are named by their service
# instead of spelling out a URL nobody would type in from paper.
def contact_entry(kind, profile)
  case kind.to_s
  when 'email'
    value = profile['email']
    value && ["mailto:#{value}", '\\faPaperPlane[solid]', "\\texttt{#{tex(value)}}"]
  when 'linkedin'
    value = profile['linkedin']
    value && ["https://www.linkedin.com/in/#{value}/", '\\faLinkedin', 'LinkedIn']
  when 'github'
    value = profile['github']
    value && ["https://github.com/#{value}", '\\faGithub', 'GitHub']
  when 'gscholar'
    value = profile['gscholar'].to_s
    return nil if value.empty?
    url = value.start_with?('http') ? value :
          "https://scholar.google.com/citations?user=#{value.split('&').first}"
    [url, '\\faGoogleScholar', 'Google Scholar']
  end
end

entries = Array(profile['cv_header_links']).map { |k| contact_entry(k, profile) }.compact
address = entries.map do |url, icon, label|
  "    \\href{#{tex_url(url)}}{#{icon}\\ \\ #{label}}"
end.join("\n    \\quad\n")

write('header.tex', <<~TEX)
  \\name{#{tex(PRIMARY_NAME)}}
  \\address{
  #{address}
  }
TEX

# --- Research interest -----------------------------------------------------

interests = Array(profile['research_interests']).map { |i| tex(i) }.join(', ')
write('research_interest.tex', section('Research Interest', interests))

# --- Education -------------------------------------------------------------

education = Array(profile['education']).map do |item|
  head = "{\\bf #{tex(item['name'])}}"
  head += ", #{tex(item['location'])}" if item['location']
  head += " \\duration{#{tex(item['date'])}}" if item['date']
  lines = Array(item['lines']).map { |l| "\\\\ {{#{tex(l)}}}" }
  ([head] + lines).join("\n")
end.join("\n\n")
write('education.tex', section('Education', education))

# --- Experience ------------------------------------------------------------

experience_items = Array(experience).map do |item|
  head = "{\\bf #{tex(item['name'])}}"
  head += ", #{tex(item['location'])}" if item['location']
  head += " \\duration{#{tex(item['date'])}}" if item['date']
  lines = [item['position'], item['dept'], item['description']].compact
          .map { |l| "        \\\\ #{tex(l)}" }
  "    \\item[] {\n        #{head}\n#{lines.join("\n")}\n    }"
end.join("\n\n")

write('experience.tex', section('Experience', <<~TEX.strip))
  \\begin{itemize}[itemsep=2pt, topsep=0pt, leftmargin=0pt]
  #{experience_items}
  \\end{itemize}
TEX

# --- Publications ----------------------------------------------------------

def author_names(authors, marks)
  Array(authors).map do |author|
    name = author.is_a?(Hash) ? author['name'] : author
    rendered = tex(name)
    rendered = "\\textbf{#{rendered}}" if name.to_s == PRIMARY_NAME
    if marks && author.is_a?(Hash)
      rendered += '$^{*}$' if author['equal_contributor']
      rendered += '$^{\\dagger}$' if author['corresponding_author']
    end
    rendered
  end
end

def author_list(authors, marks)
  names = author_names(authors, marks)
  case names.length
  when 0 then ''
  when 1 then names.first
  when 2 then names.join(' and ')
  else "#{names[0..-2].join(', ')}, and #{names.last}"
  end
end

def publication_entry(item, marks)
  venue = tex(item['venue'])
  venue = "Submitted to #{venue}" if item['type'].to_s == 'Preprint'
  year  = item['year'] ? ", #{tex(item['year'])}" : ''
  title = tex(item['title']).sub(/\.\z/, '')
  "    \\item #{author_list(item['authors'], marks)}.\n" \
  "    #{title}.\n" \
  "    \\textit{#{venue}}#{year}."
end

sorted_pubs = Array(publications).sort_by { |p| p['date'].to_s }.reverse
has_marks = AUTHOR_MARKS && sorted_pubs.any? do |p|
  Array(p['authors']).any? { |a| a.is_a?(Hash) && (a['corresponding_author'] || a['equal_contributor']) }
end

# Headings reuse the `type` labels of _data/publications.yml verbatim, so the
# CV and the website name the same group the same way.
groups = [
  ['Conference', 'C', sorted_pubs.select { |p| p['type'].to_s == 'Conference' }],
  ['Preprint',   'P', sorted_pubs.select { |p| p['type'].to_s == 'Preprint' }]
]

pub_body = +''
if has_marks
  legend = []
  legend << '$^{*}$ Equal contribution' if sorted_pubs.any? { |p| Array(p['authors']).any? { |a| a.is_a?(Hash) && a['equal_contributor'] } }
  legend << '$^{\\dagger}$ Corresponding author' if sorted_pubs.any? { |p| Array(p['authors']).any? { |a| a.is_a?(Hash) && a['corresponding_author'] } }
  # Set flush right, clear of the section rule above and tight to the first
  # group heading below.
  pub_body << "\\vspace{0.2em}\n"
  pub_body << "{\\raggedleft\\small\\textit{#{legend.join('\\quad ')}}\\par}\n"
  pub_body << "\\vspace{-1.1em}\n"
end

groups.each do |heading, label, items|
  next if items.empty?
  pub_body << "\\vspace{-2.0em}\n"
  pub_body << "\\subsection*{\\normalsize {#{heading}}}\n"
  pub_body << "\\begin{enumerate}[label={[\\textbf{#{label}\\arabic*}]}, leftmargin=2.5em]\n"
  pub_body << items.map { |item| publication_entry(item, AUTHOR_MARKS) }.join("\n")
  pub_body << "\n\\end{enumerate}\n"
end
write('publication.tex', section('Publications', pub_body))

# --- Research grants -------------------------------------------------------

grant_items = Array(grants).map do |item|
  lines = ["\\textbf{#{tex(item['name'])}} \\duration{#{tex(item['date'])}} \\\\"]
  role = [item['role'], item['funder']].compact.map { |v| tex(v) }.join(', ')
  lines << "{#{role}} \\\\" unless role.empty?
  lines << "{Total amount: #{tex(item['amount'])}}" if item['amount']
  lines.join("\n").sub(/\s*\\\\\z/, '')
end.join("\n\n")
write('research_grant.tex', section('Research Grant', grant_items)) unless Array(grants).empty?

# --- Academic service ------------------------------------------------------

if service['program_committee'] && !service['program_committee'].empty?
  items = service['program_committee'].map do |item|
    label = [item['ordinal'], item['venue']].compact.map { |v| tex(v) }.join(' ')
    label = "the #{label}" if item['ordinal']
    "        \\item[\\textopenbullet] #{label}, #{tex(item['year'])}."
  end.join("\n")

  write('academic_service.tex', section('Academic Service', <<~TEX.strip))
    {\\bf{Program Committee Member}}
    {
        \\begin{itemize}[itemsep=-5pt, topsep=-5pt, leftmargin=15pt]
    #{items}
        \\end{itemize}
    }
  TEX
end

# --- Awards ----------------------------------------------------------------

award_items = Array(awards).map do |item|
  line = "{\\bf{#{tex(item['name'])}}}"
  line += " \\duration{#{tex(item['date'])}}" if item['date']
  line += " \\\\ {#{tex(item['detail'])}}" if item['detail']
  line
end.join("\n\n")
write('award.tex', section(Array(awards).length > 1 ? 'Awards' : 'Award', award_items)) unless Array(awards).empty?

puts "Done."
